export const SET_PRODUCT = 'SET_PRODUCT'
export const PRICE_PRODUCT = 'PRICE_PRODUCT'
export const DEL_PRODUCT = 'DEL_PRODUCT'
export const DEL_PRICE = 'DEL_PRICE'
export const FILTER_PRODUCT = 'FILTER_PRODUCT'
export const DEL_FILTER = 'DEL_FILTER'
