module.exports = {
    ABOUT_AS: '/about_as',
    ADMIN_ALL: '/admin/*',
    CLIENT_ALL: '/user/*',
    CONTACT: '/contact',
    HAIR_COLOR: '/hair_color',
    HAIR_STYLES: '/hairstyles',
    LOGIN: '/login',
    MENS_HAIRCUT: '/mens_haircut',
    NOT_FOUND: '/*',
    PRODUCTS: '/products',
    PRODUCTS_ORDERS: '/products/orders',
    REGISTRATION: '/registration',
    THIS: '/',
    WOMENS_HAIRCUT: '/womens_haircut',
};
