module.exports = {
    ABOUT_AS: '/about_as',
    ADMIN_ALL: '/admin',
    ACTIVATE_TOKEN_URL: 'auth/activate/:token',
    CLIENT_ALL: '/user/*',
    CONTACT: '/contact',
    HAIR_COLOR: '/hair_color',
    HAIR_STYLES: '/hairstyles',
    LOGIN: '/login',
    LOGIN_RESET_PASSWORD: '/login-reset-password',
    MENS_HAIRCUT: '/mens_haircut',
    NOT_FOUND: '/*',
    PRODUCTS: '/products',
    PRODUCTS_ORDERS: '/products/orders',
    REGISTRATION: '/registration',
    RESET_PASSWORD: '/:user_id/reset-password',
    THIS: '/',
    UPLOAD: '/upload',
    WOMENS_HAIRCUT: '/womens_haircut',
};
