module.exports = {
    ADMIN: '/admin',
    ADMIN_ANALYSIS: '/admin/analysis',
    ADMIN_ARCHIVE_ORDERS: '/admin/archive_orders',
    ADMIN_ORDERS: '/admin/orders',
    ADMIN_RECORDS: '/admin/records',
    ADMIN_PRODUCT: '/admin/products',
    ADMIN_USERS: '/admin/users',
    ANALYSIS: 'analysis',
    ARCHIVE_ORDERS: 'archive_orders',
    CLIENT: '/user',
    CLIENT_ORDERS: '/user/orders',
    CLIENT_RECORDS: '/user/records',
    CLIENTS: 'users',
    ORDERS: 'orders',
    PRODUCT: '/product',
    PRODUCTS_CREATE: 'products',
    RECORDS: 'records',
    THIS: '/'
};
