module.exports = {
    AUTH: '/auth',
    AUTH_LOGIN: '/auth/login',
    AUTH_LOGOUT: '/auth/logout',
    AUTH_REFRESH: '/auth/refresh',
    AUTH_REGISTRATION: '/auth/registration',
    CATEGORY: '/category',
    CONTACT: '/contact',
    HOME: '/home',
    HOME_FIND: '/home/find',
    PRODUCT_ARCHIVE_ORDER: '/products/archive_order',
    PRODUCT_ORDER_ANALYZE: '/products/order_analyze',
    PRODUCT_ORDERS: '/products/orders',
    PRODUCT_ORDERS_ANALYZE_VISUAL: '/products/order_analyze_visual',
    PRODUCT_ORDERS_FILTER: '/products/orders_filter',
    PRODUCTS: '/products',
    USERS: '/users',
    USERS_ADRESS: '/users/adress',
    USERS_CONTACT: '/users/contact',
    USERS_SEND: '/users/send'
};
