module.exports = {
    WORLD_LOGIN: 'login',
    WORLD_ADMIN: 'admin',
    WORLD_USER: 'user',
    WORLD_AUTORIZATION: 'autorization',
    WORD_WAITING: 'очікується',
    WORD_LOCALES: 'uk-UA',
    WORD_OPTIONS: 'long',
    WORD_MONEY: 'Готівка',
    WORD_DAY: 'day',
    WORD_MONTH: 'month',
    WORD_WEEK: 'week',
    WORD_DEL: 'del',
    WORD_ADD: 'add',
    WORD_HIDEN: 'hiden',
    WORD_SUCCESS: 'not_success',
    WORD_CASH: 'cash',
    WORD_CART: 'cart',
    WORD_CART_UK: 'Карта',
    WORD_BORDER: 'border',
    WORD_REGISTRATION: 'Зареєструвати',
    WORD_REGISTRATING: 'Зареєструватися',
    WORD_REGISTR: 'Реєстрація',
    WORD_AUTORIZATING: 'Авторизація',
    WORD_AUTORIZ: 'Авторизуватися',
    WORD_HIDDEN: 'hidden-n-p',
    WORD_HIDDEN_ONLY: 'hidden',
    WORD_VISIBLE_N_P: 'visible-n-p',
    WORD_VISIBLE: 'visible',
    WORD_POST: 'POST',
    WORD_TOKEN: 'token',
    WORD_READY: 'готово',
    WORD_EVERY: 'все',
    WORD_EXPECTED: 'очікується',
    WORD_ACCEPTED: 'прийнято',
    WORD_PROCESSING: 'обробка',
    WORD_SEND: 'відправлено',
    WORD_LANGUAGE: 'uk',
    WORD_XLSX: 'xlsx',
    WORD_DATA: 'data',
    WORD_ARRAY: 'array',

    WORD_CATEGORY_MENU: 'category-menu',
    WORD_SMALL_MENU_ADMIN_CLIENT: 'small-menu-admin-client',
    WORD_ACTIVE_MENU_CATEGORY: 'active-menu-category',
    WORD_NO_SCROLL: 'no-scroll',
    WORD_PRODUCT_MENU_BLOCK: 'product-menu-block',

    WORD_SWAL_LATER_SEND: 'Лист відправлено',
    WORD_SWAL_SUCCESS: 'success',
    WORD_SWAL_OK: 'Ok',
    WORD_SWAL_NOT_AUTORIZE: 'Не авторизований',
    WORD_SWAL_ERROR: 'error',
    WORD_SWAL_TEXT_ERROR: 'Помилка!',
    WORD_SWAL_USER_CREATED: 'Користувач створений',
    WORD_SWAL_CATEGORY_CREATED: 'Категорія створена',
    WORD_SWAL_PRODUCT_ADD: 'Товар доданий',
    WORD_SWAL_ORDER_SEND: 'Замовлення відправлено',
    WORD_SWAL_READY: 'Готово',
};
